import type {
  CompanySettings,
  DocumentSeries,
  Employee,
  Project,
} from "./types";

export const DEMO_SETTINGS: CompanySettings = {
  id: 1,
  company_name: "CORRO CONSTRUCTION DEVELOPMENT AND TRADE CORPORATION",
  address: "15 First Street, La Guardia, Lahug, Cebu City, Cebu 6000",
  tin: null,
  document_prefix: "CCDTC",
  hr_officer_name: null,
  hr_officer_title: "HR Head",
  admin_head_name: null,
  admin_head_title: "Chief Administrative Officer",
  finance_officer_name: null,
  finance_officer_title: "Finance Head",
  ceo_name: null,
  ceo_title: "Corporate President",
  probation_warning_days: 30,
  contract_end_warning_days: 30,
  document_expiry_warning_days: 60,
  nte_answer_days: 5,
  discipline_lookback_months: 12,
  cash_advance_liquidate_days: 15,
  workdays_per_period: 13,
  overtime_multiplier: 1.0,
};

export const DEMO_PROJECTS: Project[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    name: "Cebu South Coastal Road Concreting",
    location: "Talisay, Cebu",
    status: "Active",
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    name: "Lahug Public School Building",
    location: "Lahug, Cebu City",
    status: "Active",
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    name: "Mandaue Warehouse",
    location: "Mandaue City",
    status: "Active",
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    name: "Naga Multipurpose Building",
    location: "Naga, Cebu",
    status: "Active",
  },
];

export const DEMO_DOCUMENT_SERIES: DocumentSeries[] = [
  { key: "CON", label: "Employment Contract", prefix: "", padding: 2, reset_yearly: true, pattern: "{YYYY} - {NN}" },
  { key: "NTE", label: "Notice to Explain", prefix: "NTE", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "NOD", label: "Notice of Decision", prefix: "NOD", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "WW", label: "Written Warning", prefix: "WW", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "CA", label: "Cash Advance Request Form", prefix: "CAF", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "LV", label: "Leave Request Form", prefix: "LRF", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "COE", label: "Certificate of Employment", prefix: "COE", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "CLR", label: "Clearance / Quitclaim", prefix: "CLR", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "CM", label: "Company Memorandum", prefix: "C.M. ", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "DM", label: "Disciplinary Memorandum", prefix: "DM", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "NCR", label: "Non-Conformance Report", prefix: "NCR", padding: 3, reset_yearly: true, pattern: "{PREFIX} {YYYY} - {NNN}" },
  { key: "ALR", label: "Acceptance of Resignation", prefix: "ALR", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NN}" },
  { key: "RM", label: "Written Reminder", prefix: "RM", padding: 3, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNN}" },
  { key: "RFFI", label: "Recommendation for Final Interview", prefix: "RFFI", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "IR", label: "Incident Report", prefix: "IR", padding: 2, reset_yearly: true, pattern: "{PREFIX}{YYYY} - {NN}" },
  { key: "PE", label: "Performance Evaluation", prefix: "PE", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "OFR", label: "Job Offer", prefix: "OFR", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "PAF", label: "Personnel Action Form", prefix: "PAF", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
  { key: "MEMO", label: "Memorandum", prefix: "MEMO", padding: 4, reset_yearly: true, pattern: "{PREFIX}{YYYY}-{NNNN}" },
];

const MARIA = "30000000-0000-4000-8000-000000000001";
const JUAN = "30000000-0000-4000-8000-000000000002";
const ANA = "30000000-0000-4000-8000-000000000003";
const JOSE = "30000000-0000-4000-8000-000000000004";
const ROSA = "30000000-0000-4000-8000-000000000005";
const CARLO = "30000000-0000-4000-8000-000000000006";
const LIGAYA = "30000000-0000-4000-8000-000000000007";
const PEDRO = "30000000-0000-4000-8000-000000000008";
const COASTAL = "20000000-0000-4000-8000-000000000001";
const NAGA = "20000000-0000-4000-8000-000000000004";

export const DEMO_EMPLOYEES: Employee[] = [
  {
    id: MARIA,
    emp_no: "1353",
    name: "Dela Cruz, Maria S.",
    nickname: "Maring",
    birthdate: "1988-04-12",
    sex: "Female",
    civil_status: "Married",
    address: "Lahug, Cebu City",
    mobile: "0917-555-1353",
    email: "maria.delacruz@corcondev.local",
    emergency_name: "Ramon Dela Cruz",
    emergency_relation: "Spouse",
    emergency_number: "0917-555-2001",
    sss_no: "33-1234567-8",
    tin_no: "123-456-789-000",
    philhealth_no: "12-345678901-2",
    pagibig_no: "1211-1234-5678",
    bank_account: "BDO 001234567890",
    department: "hr",
    position: "HR Officer",
    project: null,
    project_id: null,
    project_location: "Main Office / Motorpool",
    supervisor: null,
    supervisor_id: null,
    employment_status: "Regular",
    date_hired: "2019-03-11",
    contract_start: "2019-03-11",
    contract_end: null,
    prior_contract_no: null,
    regularized_on: "2019-09-11",
    daily_rate: 1200,
    rate_type: "Monthly",
    allowance: 0,
    separated_on: null,
    separation_reason: null,
    status_basis: "Office staff on monthly payroll; no project assignment.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample office regular. Not a live employee record.",
    checklist: [],
  },
  {
    id: JUAN,
    emp_no: "1108",
    name: "Santos, Juan P.",
    nickname: "Johnny",
    birthdate: "1994-11-03",
    sex: "Male",
    civil_status: "Single",
    address: "Talisay City, Cebu",
    mobile: "0918-555-1108",
    email: "juan.santos@corcondev.local",
    emergency_name: "Lorna Santos",
    emergency_relation: "Mother",
    emergency_number: "0918-555-2108",
    sss_no: "34-7654321-0",
    tin_no: "321-654-987-000",
    philhealth_no: "13-987654321-0",
    pagibig_no: "1211-8765-4321",
    bank_account: "BPI 009988776655",
    department: "site",
    position: "Mason",
    project: "Cebu South Coastal Road Concreting",
    project_id: COASTAL,
    project_location: "Talisay, Cebu",
    supervisor: "Garcia, Jose M.",
    supervisor_id: JOSE,
    employment_status: "Project-based",
    date_hired: "2024-06-01",
    contract_start: "2026-06-01",
    contract_end: "2026-11-30",
    prior_contract_no: "2025 - 88",
    regularized_on: null,
    daily_rate: 620,
    rate_type: "Daily",
    allowance: 50,
    separated_on: null,
    separation_reason: null,
    status_basis: "Assigned to an active project; successive project contracts.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample project-based mason.",
    checklist: [],
  },
  {
    id: ANA,
    emp_no: "1422",
    name: "Reyes, Ana L.",
    nickname: "Annette",
    birthdate: "1999-07-21",
    sex: "Female",
    civil_status: "Single",
    address: "Mandaue City",
    mobile: "0927-555-1422",
    email: "ana.reyes@corcondev.local",
    emergency_name: "Elena Reyes",
    emergency_relation: "Mother",
    emergency_number: "0927-555-2422",
    sss_no: "35-1122334-5",
    tin_no: "111-222-333-000",
    philhealth_no: "14-112233445-5",
    pagibig_no: "1211-1122-3344",
    bank_account: "Metrobank 1122334455",
    department: "finance",
    position: "Accounting Clerk",
    project: null,
    project_id: null,
    project_location: "Main Office / Motorpool",
    supervisor: "Dela Cruz, Maria S.",
    supervisor_id: MARIA,
    employment_status: "Probationary",
    date_hired: "2026-07-01",
    contract_start: "2026-07-01",
    contract_end: "2026-12-31",
    prior_contract_no: null,
    regularized_on: null,
    daily_rate: 850,
    rate_type: "Monthly",
    allowance: 0,
    separated_on: null,
    separation_reason: null,
    status_basis: "Probationary office hire; regularization review before contract end.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample probationary clerk.",
    checklist: [],
  },
  {
    id: JOSE,
    emp_no: "1280",
    name: "Garcia, Jose M.",
    nickname: "Jojo",
    birthdate: "1985-01-30",
    sex: "Male",
    civil_status: "Married",
    address: "Cebu City",
    mobile: "0916-555-1280",
    email: "jose.garcia@corcondev.local",
    emergency_name: "Teresa Garcia",
    emergency_relation: "Spouse",
    emergency_number: "0916-555-2280",
    sss_no: "33-9988776-1",
    tin_no: "998-877-661-000",
    philhealth_no: "12-998877661-1",
    pagibig_no: "1211-9988-7766",
    bank_account: "BDO 009988776611",
    department: "technical",
    position: "Project Engineer",
    project: "Cebu South Coastal Road Concreting",
    project_id: COASTAL,
    project_location: "Talisay, Cebu",
    supervisor: "Dela Cruz, Maria S.",
    supervisor_id: MARIA,
    employment_status: "Project-based",
    date_hired: "2021-02-15",
    contract_start: "2026-03-01",
    contract_end: "2026-12-15",
    prior_contract_no: "2025 - 12",
    regularized_on: null,
    daily_rate: 1400,
    rate_type: "Daily",
    allowance: 200,
    separated_on: null,
    separation_reason: null,
    status_basis: "Site assignment; project-based regardless of length of service.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample project engineer / site supervisor.",
    checklist: [],
  },
  {
    id: ROSA,
    emp_no: "1510",
    name: "Mendoza, Rosa C.",
    nickname: "Osang",
    birthdate: "1991-09-18",
    sex: "Female",
    civil_status: "Married",
    address: "Naga, Cebu",
    mobile: "0933-555-1510",
    email: "rosa.mendoza@corcondev.local",
    emergency_name: "Carlo Mendoza",
    emergency_relation: "Spouse",
    emergency_number: "0933-555-2510",
    sss_no: "34-5566778-9",
    tin_no: "556-677-889-000",
    philhealth_no: "13-556677889-0",
    pagibig_no: "1211-5566-7788",
    bank_account: "Landbank 5566778899",
    department: "safety",
    position: "Safety Officer",
    project: "Naga Multipurpose Building",
    project_id: NAGA,
    project_location: "Naga, Cebu",
    supervisor: "Garcia, Jose M.",
    supervisor_id: JOSE,
    employment_status: "Project-based",
    date_hired: "2023-05-08",
    contract_start: "2026-05-08",
    contract_end: "2026-11-08",
    prior_contract_no: "2025 - 44",
    regularized_on: null,
    daily_rate: 780,
    rate_type: "Daily",
    allowance: 80,
    separated_on: null,
    separation_reason: null,
    status_basis: "Assigned to Naga site.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample safety officer.",
    checklist: [],
  },
  {
    id: CARLO,
    emp_no: "1604",
    name: "Villanueva, Carlo T.",
    nickname: "Caloy",
    birthdate: "1997-12-05",
    sex: "Male",
    civil_status: "Single",
    address: "Consolacion, Cebu",
    mobile: "0947-555-1604",
    email: "carlo.villanueva@corcondev.local",
    emergency_name: "Nita Villanueva",
    emergency_relation: "Sister",
    emergency_number: "0947-555-2604",
    sss_no: "36-4455667-8",
    tin_no: "445-566-778-000",
    philhealth_no: "15-445566778-8",
    pagibig_no: "1211-4455-6677",
    bank_account: null,
    department: "unassigned",
    position: "Laborer",
    project: null,
    project_id: null,
    project_location: null,
    supervisor: null,
    supervisor_id: null,
    employment_status: null,
    date_hired: "2026-08-20",
    contract_start: null,
    contract_end: null,
    prior_contract_no: null,
    regularized_on: null,
    daily_rate: 520,
    rate_type: "Daily",
    allowance: 0,
    separated_on: null,
    separation_reason: null,
    status_basis: "Roster imported; classification not yet set.",
    roster_confirmed: null,
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample unclassified record — employment_status left blank on purpose.",
    checklist: [],
  },
  {
    id: LIGAYA,
    emp_no: "1377",
    name: "Ramos, Ligaya F.",
    nickname: "Gaya",
    birthdate: "1982-06-14",
    sex: "Female",
    civil_status: "Widowed",
    address: "Cebu City",
    mobile: "0915-555-1377",
    email: "ligaya.ramos@corcondev.local",
    emergency_name: "Paolo Ramos",
    emergency_relation: "Son",
    emergency_number: "0915-555-2377",
    sss_no: "33-2233445-6",
    tin_no: "223-344-556-000",
    philhealth_no: "12-223344556-6",
    pagibig_no: "1211-2233-4455",
    bank_account: "BDO 223344556677",
    department: "procurement",
    position: "Purchasing Assistant",
    project: null,
    project_id: null,
    project_location: "Main Office / Motorpool",
    supervisor: "Dela Cruz, Maria S.",
    supervisor_id: MARIA,
    employment_status: "Fixed-term",
    date_hired: "2025-01-06",
    contract_start: "2026-01-06",
    contract_end: "2026-12-31",
    prior_contract_no: "2025 - 02",
    regularized_on: null,
    daily_rate: 900,
    rate_type: "Monthly",
    allowance: 0,
    separated_on: null,
    separation_reason: null,
    status_basis: "Fixed-term office engagement.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample fixed-term procurement staff.",
    checklist: [],
  },
  {
    id: PEDRO,
    emp_no: "0901",
    name: "Bautista, Pedro A.",
    nickname: "Pete",
    birthdate: "1978-02-09",
    sex: "Male",
    civil_status: "Married",
    address: "Minglanilla, Cebu",
    mobile: "0922-555-0901",
    email: "pedro.bautista@corcondev.local",
    emergency_name: "Alicia Bautista",
    emergency_relation: "Spouse",
    emergency_number: "0922-555-2901",
    sss_no: "33-6677889-0",
    tin_no: "667-788-990-000",
    philhealth_no: "12-667788990-0",
    pagibig_no: "1211-6677-8899",
    bank_account: "BPI 667788990011",
    department: "motorpool",
    position: "Mechanic (Consultant)",
    project: null,
    project_id: null,
    project_location: "Main Office / Motorpool",
    supervisor: null,
    supervisor_id: null,
    employment_status: "Consultant",
    date_hired: "2024-10-01",
    contract_start: "2026-01-01",
    contract_end: "2026-12-31",
    prior_contract_no: null,
    regularized_on: null,
    daily_rate: 1500,
    rate_type: "Daily",
    allowance: 0,
    separated_on: null,
    separation_reason: null,
    status_basis: "Yard assignment — Main Office / Motorpool is not a project.",
    roster_confirmed: "2026-08-15",
    photo_link: null,
    drive_folder_id: null,
    drive_folder_link: null,
    notes: "Sample motorpool consultant.",
    checklist: [],
  },
];
